# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Theme Settings
#
# Review documentation to determine if you should use `theme` or `remote_theme`
# https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/#installing-the-theme

theme                    : "jekyll-theme-cayman"


# Site Settings
locale                   : "en-US"
title                    : "Welcome to the Jeff Yoon's page"
title_separator          : "-"
subtitle                 : # site tagline that appears below site title in masthead
name                     : "Jeff Yoon"
description              : "Jeff Yoon's personal website."
url                      : "https://jeffyoon.github.io"
